server:
  port: 8761 #æŒ‡å®šæœåŠ¡ç«¯å£
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false #æ˜¯å¦å°†eurekaè‡ªèº«ä½œä¸ºåº”ç”¨æ³¨å†Œåˆ°eurekaæ³¨å†Œä¸­å¿ƒ
    fetchRegistry:  false
    healthcheck:
      enabled: true # å¼?å¯å¥åº·æ£€æŸ¥ï¼ˆéœ?è¦spring-boot-starter-actuatorä¾èµ–ï¼?
    instance:
      hostname: localhost
      lease-expiration-duration-in-seconds: 30 # ç»­çº¦æ›´æ–°æ—¶é—´é—´éš”ï¼ˆé»˜è®?30ç§’ï¼‰
      lease-renewal-interval-in-seconds: 10 # ç»­çº¦åˆ°æœŸæ—¶é—´ï¼ˆé»˜è®?90ç§’ï¼‰
  server:
      enable-self-preservation: true # è®¾ä¸ºfalseï¼Œå…³é—­è‡ªæˆ‘ä¿æŠ?
      eviction-interval-timer-in-ms: 4000  # æ¸…ç†é—´éš”ï¼ˆå•ä½æ¯«ç§’ï¼Œé»˜è®¤æ˜?60*1000ï¼?

